### ISSUE TITLE
`stopOnError` inside `xclap.js` does nothing

### ISSUE THREAD

**Issue by theVeid** [jchip/xclap#14]
There is a repository to reproduce this error https://github.com/theVeid/xclap-soe-issue

There are two tasks, that are running concurrently and both of them exit with process code not equal 0. When defining `xclap.stopOnError = 'soft'` inside `xclap.js`, it is expected that after first task exits xclap will wait until the second task finish too, but it is not the case until one define `--soe soft` flag for xclap cli launch

### Expected Behaviour
Same result expected for both `no-flag` and `flag` command, as `stopOnError` is defined inside `xclap.js` file

### Current Behaviour
`no-flag` command will stop fully after error in first exited task, no matter that `stopOnError` is defined with `soft` inside `xclap.js`

**Comment by jchip** [comment]
Hi, thanks for reporting this and taking the time to create a repro sample.  It's very helpful.

Note that the `flag` behavior is implemented to how I think it should work.  I figured what user specify in the CLI should have the ultimate voting power.

but the `no-flag` behavior is wrong.  fixed in 0.2.31.
